set -g base-index 1 # start windows numbering at 1
bind -T prefix s choose-tree -s -Z -K "#{?#{e|<:#{line},9},#{e|+:#{line},1},#{?#{e|<:#{line},36},M-#{a:#{e|+:97,#{e|-:#{line},10}}},}}" # start session numbering at 1: https://www.reddit.com/r/tmux/comments/fsuy7e/comment/lz6rnpu/

set -s escape-time 0      # Fixes vim escape lag
set -g repeat-time 0      # Fixes input lag after switching panes
set -g focus-events on    # Passes focus events to apps (vim)

set -g mouse on

set -g prefix C-Space
unbind C-b

set -g history-limit 10000

# vim-like splits
bind n switch-client -T newpane
bind -T newpane h split-window -h \; select-pane -L \; switch-client -T root
bind -T newpane j split-window -v \; select-pane -D \; switch-client -T root
bind -T newpane k split-window -v \; select-pane -U \; switch-client -T root
bind -T newpane l split-window -h \; select-pane -R \; switch-client -T root
bind -T newpane Escape switch-client -T root
bind -T newpane q switch-client -T root

bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

# copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi j send-keys -X cursor-up
bind-key -T copy-mode-vi k send-keys -X cursor-down
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key y run-shell "tmux capture-pane -pS - -E - > /tmp/tmux_#S_#I ; tmux new-window -n 'scrollback' \"nvim + '/tmp/tmux_#S_#I' -c 'setlocal buftype=nofile bufhidden=wipe noswapfile'\""

# swap up and down in pane/tree mode
bind-key -T root j if-shell -F "#{==:#{pane_mode},tree-mode}" "send-keys Up" "send-keys j"
bind-key -T root k if-shell -F "#{==:#{pane_mode},tree-mode}" "send-keys Down" "send-keys k"

bind h clear-history

# active borders
set -g pane-active-border-style "fg=#6881c2"

# scroll one line
bind -Tcopy-mode WheelUpPane send -N1 -X scroll-up
bind -Tcopy-mode WheelDownPane send -N1 -X scroll-down


set -g @plugin 'niksingh710/minimal-tmux-status'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
