[settings]
mouse_follows_focus = false
focus_follows_mouse = false
hot_reload = true
default_disable = false
run_on_start = ["sketchybar"]

[settings.layout]
mode = "traditional"

[settings.layout.gaps]
outer.top = 60
outer.left = 15
outer.right = 15
outer.bottom = 15
inner.horizontal = 15
inner.vertical = 15

[settings.gestures]
enabled = true

[virtual_workspaces]
enabled = true
default_workspace_count = 10
default_workspace = 1
workspace_auto_back_and_forth = false
preserve_focus_per_workspace = true

app_rules = [
  { app_id = "com.apple.Safari", title_regex = "Bitwarden", floating = true },
  { app_id = "com.spotify.client",        workspace = 9 },
  { app_id = "com.apple.ActivityMonitor", workspace = 6 },
  { app_id = "com.apple.iCal",            workspace = 6 },
  { app_id = "us.zoom.xos",               workspace = 6 },
  { app_id = "com.tinyspeck.slackmacgap", workspace = 7 },
  { app_id = "com.docker.docker",         workspace = 8 },
  { app_id = "com.apple.MobileSMS",       workspace = 7 },
  { app_name = "Discord",                 workspace = 7 },
]

[modifier_combinations]
alt-s = "Alt + Shift"
alt-c = "Alt + Control"

[keys]
"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "up" }
"Alt + K" = { move_focus = "down" }
"Alt + L" = { move_focus = "right" }

"alt-s + H" = { move_node = "left" }
"alt-s + J" = { move_node = "up" }
"alt-s + K" = { move_node = "down" }
"alt-s + L" = { move_node = "right" }

"Alt + Minus" = "resize_window_shrink"
"Alt + Equal" = "resize_window_grow"

"Alt + Slash" = "toggle_orientation"

"alt-s + F" = "toggle_fullscreen_within_gaps"

"alt-s + T" = "toggle_window_floating"

"Alt + 1" = { switch_to_workspace = 1 }
"Alt + 2" = { switch_to_workspace = 2 }
"Alt + 3" = { switch_to_workspace = 3 }
"Alt + 4" = { switch_to_workspace = 4 }
"Alt + 5" = { switch_to_workspace = 5 }
"Alt + 6" = { switch_to_workspace = 6 }
"Alt + 7" = { switch_to_workspace = 7 }
"Alt + 8" = { switch_to_workspace = 8 }
"Alt + 9" = { switch_to_workspace = 9 }

"alt-s + 1" = { move_window_to_workspace = 1 }
"alt-s + 2" = { move_window_to_workspace = 2 }
"alt-s + 3" = { move_window_to_workspace = 3 }
"alt-s + 4" = { move_window_to_workspace = 4 }
"alt-s + 5" = { move_window_to_workspace = 5 }
"alt-s + 6" = { move_window_to_workspace = 6 }
"alt-s + 7" = { move_window_to_workspace = 7 }
"alt-s + 8" = { move_window_to_workspace = 8 }
"alt-s + 9" = { move_window_to_workspace = 9 }

"Alt + Tab" = "switch_to_last_workspace"

# shortcuts
"alt-c + T" = { exec = "/Applications/Ghostty.app/Contents/MacOS/ghostty" }
"alt-c + S" = { exec = ["/bin/sh", "-c", "osascript -e 'tell application \"Safari\" to make new document at end of documents' -e 'tell application \"Safari\" to activate'"] }
"alt-c + C" = { exec = ["/bin/sh", "-c", "osascript -e 'tell application \"/Applications/Helium.app\" to make new window' -e 'tell application \"/Applications/Helium.app\" to activate'"] }

"Alt + Z" = "toggle_space_activated"
